name: Test Nix Flake

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          recursive: true

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: nix flake check for all platforms
        run: |
          nix flake check --all-systems

  nix-build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          recursive: true

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: nix build . for x86_64-linux
        run: nix build .

  nix-build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          recursive: true

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: nix build . for x86_64-darwin
        run: nix build .

